### ISSUE TITLE
Workflow in Github aufsetzen, um die App für Android automatisch zu bauen

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#111]
In Github kann eine CI-Aktion angelegt werden, um die App für Android (evtl. für iOs) automatisch zu bauen und als Binary unter "Release" abzulegen.

Eine Anleitung dazu ist hier zu finden: https://prin53.medium.com/github-actions-xamarin-apps-231a65642631

**Comment by Sratschka** [comment]
App wird bei jedem größeren update manuell gebaut
