### ISSUE TITLE
Pagination bei Herausforderungen

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#112]
Aktuell werden im Backend und der App alle Herausforderungen auf einmal geladen.
Hier sollte eine Pagination realisiert werden. 

Zu tun:
1) Restful API api anpassen, um Ergebnisse schrittweise laden zu können (die Repsitories können das schon).
2) Backend anpassen, so dass schrittweise jeweils 10 Elemente geladen werden und man zwischen den Seiten springen kann.
3) In der App entsprechendes einbauen. Dazu sollte die Eigenschaft "ItemsTreshold" der CollectionView benutzt werden.

**Comment by CharlotteLueb** [comment]
siehe auch #91

**Comment by LosWochos76** [comment]
Done
