### ISSUE TITLE
Erreichbarkeit https://studybuddy.hshl.de/ aus hshl-stud wlan

### ISSUE THREAD

**Issue by Sratschka** [LosWochos76/StudyBuddy#118]
Nach Tests mit fünf anderen Student:innen scheint https://studybuddy.hshl.de/ aus dem hshl-stud wlan aktuell nicht erreichbar zu sein. Über mobile Daten hat es bei jedem funktioniert.

**Comment by winfep** [comment]
Sowohl Webseite als auch App sind jetzt erreichbar.
