### ISSUE TITLE
Einstellungen 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#130]
Was muss unter den Einstellungen alles auftauchen?

- [ ] #82 
- [ ] Name ändern
- [ ] Nickname ändern
- [ ] Profilbild ändern

_Die E-Mail Adresse sollte man nicht ändern können_

**Comment by Sratschka** [comment]
Soll über die App die Verwaltung des Nutzerkontos (Profilbild, Nickname, etc.) möglich sein?

**Comment by LosWochos76** [comment]
Ja.
