### ISSUE TITLE
In der App swipen zwischen Seiten integrieren

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#132]

**Comment by Sratschka** [comment]
Swipen zwischen den tabs (Herausforderungen, Freunde, Statistiken, etc) oder innerhalb der tabs (zB innerhalb von "Herausforderungen" verschiedene Seiten wie "Latest"/"For Today"/"Last Chance"?

**Comment by LosWochos76** [comment]
Innerhalb eines Tabs, also z.B. bei den Neuigkeiten zwischen "Freunde" und "Anfragen".
