### ISSUE TITLE
Test Kontrollabgabe: Erstellung Badges und Herausforderungen durch Dozenten

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#133]
Wie sieht es letztendlich wirklich aus, wenn Badges nur noch mit Tags und nicht mehr mit Herausforderungen verknüpft sind? Kommt es zu Problemen, dadurch das neue Challenges mit einem Tag versehen werden, welches andere bereits für ein Abzeichen verwendet haben, wo jedoch die neu angelegte Challenge gar nicht mit reinspielen soll?

**Comment by LosWochos76** [comment]
Ein einmal verliehenes Abzeichen wird nicht wieder zurückgezogen. Aber ich bin mir nicht sicher, ob das hier die Frage war?
