### ISSUE TITLE
Styleguide für die App schreiben

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#137]
Es arbeiten nun mehrere Entwickler an der App. Leider sieht die App auch entsprechend aus. Je nachdem, in welcher Page man sich befindet, werden doch sehr unterschiedliche Interaktionsmodelle/Styles/Designs benutzt. Mal werden abgerundete Frames mit Schattenwurf benutzt, mal nicht. Mal werden Elemente in Listen durch Trennstrich abgetrennt, mal nicht. Wir brauchen aber unbedingt ein durchgängiges Design in der App.

Es sollte ein Styleguide definiert werden, der festlegt, wie bestimmte Interaktionen/Szenarien auf UI-Elemente in der App abgebildet werden sollen. Dieser sollte sich an dem durchgängigen Design orientieren, welches von Frau Lueb in dem Prototyp definiert wurde.

Folgende Fragen sollen beantwortet werden:
- Wie wird mit Farbe umgegangen? Welche Farben sollten benutzt werden? Wie/wo?
- Wie wird Text dargestellt, Textgröße/Font/Fettschrift?
- Wo werden Frames benutzt, wo nicht? Runde Ecken um Frames, ja/nein?
- Schattenwurf um Frames/Controls, ja/nein?
- Wie sehen Buttons generell aus?

An den Styleguide sollen sich alle Entwickler halten.

**Comment by CharlotteLueb** [comment]
Der Darkmode wird vorübergehend außenvorgelassen.
