### ISSUE TITLE
Erfolg einer Herausforderung -> bei nur einem Nutzer „haben“ in „hat“ umändern

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#142]
![Bild1](https://user-images.githubusercontent.com/85349413/143500195-063055c8-6ef7-4e6d-85de-11331106b7e2.png)

**Comment by Smil3MoreGH** [comment]
Satz heißt jetzt "Die Herausforderung ... wurde bislang von ... Nutzer(n) angenommen."
So ist der Satz neutral und passt für beide Fälle
