### ISSUE TITLE
Möglichkeit einem Abzeichen ein Bild beizufügen 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#150]
Wenn man ein Abzeichen anlegt, ermöglichen diesem ein personalisiertes Bild beizufügen. So wird dann beispielsweise nicht mehr eine Medaille in Bronze, Silber oder Gold angezeigt, sondern eine personalisierte Medaille. 

Dies ist nur ein zusätzliches Feature und keinerlei verpflichtend. Es dient nur dazu, die Abzeichen optisch schöner zu gestalten.

**Comment by LosWochos76** [comment]
Das sollte man evlt. mit FontAwesome lösen. Dadurch ist dann die Skalierbarkeit und gleiche Darstellung auf mobilen Endgeräten und Web sichergestellt.
