### ISSUE TITLE
Bestätigungsemail beim Anlegen eines Nutzers

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#159]
Erst nachdem man der Bestätigungsaufforderung in der Mail nachgekommen ist, wird der Account des Nutzers angelegt. Dadurch wird unterbunden, dass Personen einen Account für eine andere beziehungsweise fremde Person ohne dessen Wissen anlegen können.

**Comment by Sratschka** [comment]
Ist in Arbeit
