### ISSUE TITLE
Doppeltes Stellen und Annehmen einer Freundschaftsanfrage 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#160]
Dato kann man Freundschaftsanfragen an eine Person zweimal stellen und auch beide annehmen. Daraufhin taucht der Freund auch zweimal in der Freundesliste auf. Dies sollte so nicht sein

**Comment by LosWochos76** [comment]
Ist in der API gefixed. Bevor ein neues Request-Objekt in der DB gespeichert wird, wird geprüft, ob es ein ähnliches Objekt bereits gibt. Wenn ja, wird dieses existierende Objekt zurückgegeben, anstelle eines neuen Objekts.
