### ISSUE TITLE
Beweiserbringung „Systembeweis“ beim Anlegen einer Herausforderung ergänzen

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#161]
Bei der Auswahl dieser Beweismethode, wird die Herausforderung „automatisch“ durch das System bestätigt. Diese Methode der Beweiserbringung muss erst angefragt werden.

**Comment by CharlotteLueb** [comment]
Wichtig: Diese Beweiserbringung darf nur Administratoren zur Verfügung stehen

**Comment by LosWochos76** [comment]
Done
