### ISSUE TITLE
Fehlermeldung einfügen, wenn keine Internetverbindung besteht

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#164]
Aufforderung einfügen, sich erneut mit dem Internet zu verbinden

**Comment by Smil3MoreGH** [comment]
Funktion App_ConnectivityChanged in App.xaml.cs eingeführt, welche genau dies macht.
Siehe Commit: [https://github.com/LosWochos76/StudyBuddy/commit/f96be266096bf4af7da7b8232605b656b3318a60](url)

**Comment by winfep** [comment]
Heute die App auf dem IPad (IOS) ohne Internetverbindung geöffnet. Die App ist ohne Kommentar abgestürzt. Nach Aktivierung der Internetverbindung konnte die App ohne Fehler geöffnet werden.
