### ISSUE TITLE
Beweiserbringung „Durch Bestätigung eines Freundes“ gendern 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#170]
Vorschläge: 
„Durch Bestätigung eines/einer Freundes/Freundin“ 
„Durch ein:e Freund:in“

**Comment by Smil3MoreGH** [comment]
Angepasst in der App, siehe:
https://github.com/LosWochos76/StudyBuddy/commit/0e7ecb3cec9cfa976cf4d2c1d2572bbbe3eca749

Fehlt noch Anpassung im Backend
