### ISSUE TITLE
Herausforderung durch „Abschließen“ direkt aus der Liste verschwinden lassen 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#171]
Nach dem Annehmen einer Herausforderung, erscheint sie trotzdem noch in der Liste der Herausforderungen. Erst nachdem die Seite durch Runterziehen aktualisiert wird, ist die Herausforderung nicht mehr da.

**Comment by Smil3MoreGH** [comment]
Gelöst in:
[https://github.com/LosWochos76/StudyBuddy/commit/1c4353a3ee3463436d4da731f7aa562c9ded4973](url)
