### ISSUE TITLE
Beschreibungen beim Anlegen einer Herausforderung verpflichtend machen 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#174]
Dato muss man bei einer Herausforderung nur einen Namen eingeben. Die Beschreibung kann man unausgefüllt lassen. Im Allgemeinen ist es sinnvoll, eine Beschreibung einzugeben, damit der Studierende genau weiß, was man machen muss, um die Herausforderung zu bestehen. Insbesondere wird die Beschreibung aber dann wichtig, wenn das Beweisverfahren „Schlüsselwort“ verwendet wird. Dann muss in der Beschreibung genau vermerkt werden, was genau beim Schlüsselwort gesucht wird.

**Comment by Smil3MoreGH** [comment]
sollte in 77a14c7 behoben sein.
