### ISSUE TITLE
Button „Herausforderung Abschließen“ abschließen klein schreiben

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#177]
In der Detailansicht der Herausforderung den Button von „Herausforderung Abschließen“ in „Herausforderung abschließen“ ändern
![Bild4](https://user-images.githubusercontent.com/85349413/149381149-406a62ee-0e48-425b-9ab8-0c47c93ce8d6.png)
oder wie in der Android Version komplett in Versalien schreiben „HERAUSFORDERUNG ABSCHLIESSEN“

**Comment by Smil3MoreGH** [comment]
Ist behoben worden
