### ISSUE TITLE
Statusbar im Darkmode des iPads kaum lesbar 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#178]
Wenn das Gerät auf Darkmode gestellt ist, kann man die Statusbar kaum erkennen:
![Bild5](https://user-images.githubusercontent.com/85349413/149381340-5acd99db-bec2-4263-b35c-620306ac2659.png)

Hier im Vergleich, wenn das Gerät auf Lightmode gestellt ist:
![Bild6](https://user-images.githubusercontent.com/85349413/149381379-84ac73bf-ba46-42db-a9bf-03ae58708116.png)

**Comment by Smil3MoreGH** [comment]
Muss einmal mit der neu erstellten Version getestet werden

**Comment by Sratschka** [comment]
resolved
