### ISSUE TITLE
Bei Profileinstellungen „Passwort“ und „Passwort bestätigen“ mit Sternchen oder Punkten ersetzen

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#183]
Bei Profileinstellungen Text in den Feldern bei „Passwort“ und „Passwort bestätigen“ als Sternchen oder Punkte (passend zu der Buchstabenanzahl des bestehenden Passwortes) darstellen
![Bild10](https://user-images.githubusercontent.com/85349413/149382504-c54e23d9-aed6-4d9d-82ff-be9df7eedf1a.png)

**Comment by Smil3MoreGH** [comment]
![image](https://user-images.githubusercontent.com/73059580/151710678-bea98971-e304-4e1d-b01c-ab7b4d8a998b.png)
Ist in einem Update von Herrn Turner eingeführt worden.
