### ISSUE TITLE
Man kann keine Freundschaftsanfragen verschicken 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#186]
![Bild12](https://user-images.githubusercontent.com/85349413/149382989-0c966dfe-2715-43f7-b22f-94c108e6613a.png)
In der Freundesliste taucht kein Button „Freundschaft anfragen“ auf und es ist auch nicht möglich, durch eine Detailansicht (wie bei den Herausforderungen) zu dem Button zu gelangen

**Comment by Smil3MoreGH** [comment]
Sollte gehen, eventuell hast du noch eine alte Version? 🤔
![image](https://user-images.githubusercontent.com/73059580/149385992-ee47619e-6705-41cb-94eb-efd0fe32bab3.png)

**Comment by Smil3MoreGH** [comment]
Wenn ich die APK vom 10 Januar installiere ist das bei mir auch nicht sichtbar. Scheint also ein relativ neues update der letzten paar Tage gewesen zu sein.
In der aktuellen Version auf meinem Rechner sind die Buttons da. Sollte also in der nächsten Version dabei sein 👍.

**Comment by CharlotteLueb** [comment]
Okay perfekt, dann schließe ich damit das Ticket wieder!
