### ISSUE TITLE
Infotext im Login Screen mit Lücke dargestellt 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#187]
![Bild13](https://user-images.githubusercontent.com/85349413/149383116-6b77913d-d7a8-45fc-b40e-d897b778a4cf.png)

**Comment by Smil3MoreGH** [comment]
Scheint bei Android und IOS zu sein, wenn man die App im Querformat hat (oder auf einem großen Gerät wie z.B einem IPad)

**Comment by Smil3MoreGH** [comment]
Sollte behoben sein, habe ein Unicode-Zeilenvorschubzeichen (& #10;) eingefügt, siehe commit:
https://github.com/LosWochos76/StudyBuddy/commit/b59c94db9378f6eace8100e96dde60e5e6fc27e5
