### ISSUE TITLE
 Schreibfehler bei „Wilkommen“ im Login Screen 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#188]
![Bild14](https://user-images.githubusercontent.com/85349413/149383303-36bb9ed5-e848-4852-9417-8bc19a2b3d47.png)

**Comment by Smil3MoreGH** [comment]
Behoben, siehe commit:
[https://github.com/LosWochos76/StudyBuddy/commit/b59c94db9378f6eace8100e96dde60e5e6fc27e5](url)
