### ISSUE TITLE
Einwilligungserklärung vor dem erstmaligen Gebrauch einholen

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#193]
Einen Informationstext mit Hyperlink zur Datenschutzerklärung bei der Registrierung eines neuen Users einfügen, den man aktiv durch eine Checkbox als gelesen und akzeptiert markieren muss. Erst danach ist eine erfolgreiche Registrierung möglich.

**Comment by LosWochos76** [comment]
Done
