### ISSUE TITLE
Beim Registrieren prüfen, ob es sich bei der HSHL E-Mail-Adresse, um eine wirklich bestehende handelt 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#198]
Bis jetzt wird nicht geprüft, ob die HSHL E-Mail wirklich vergeben ist oder nur fiktiv ist

**Comment by LosWochos76** [comment]
Genau dafür ist ja die Willkommens-Mail da, in der man einen Link klicken muss, um den Account zu bestätigen.

**Comment by CharlotteLueb** [comment]
Okay, dann ist das Ticket überflüssig.
