### ISSUE TITLE
Löschen des Kontos ermöglichen 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#199]
Der Benutzer (Studierende, wie auch Dozenten) sollten die Möglichkeit haben ihr komplettes Konto und die damit verbundenen Daten zu löschen oder zu deaktivieren.

**Comment by Sratschka** [comment]
Reminder: Gelöschte benutzer sollten nicht mehr in den Vorschlägen neuer Freunde auftauchen.
![friendrequests](https://user-images.githubusercontent.com/65534758/169509649-c701db95-4d88-440d-bf53-961a2597641c.PNG)

**Comment by Sratschka** [comment]
Deaktivieren eines Kontos ist in der App möglich und reaktiviert wird über "gameucation.eu/recover", zum vollständigen Löschen muss eine mail geschickt werden.
