### ISSUE TITLE
Schattierung erster Eintrag Liste Challenges IOS nicht homogen zu Rest der Liste

### ISSUE THREAD

**Issue by winfep** [LosWochos76/StudyBuddy#200]
![Photo-2022-02-10-09-57-30_0003](https://user-images.githubusercontent.com/82937602/153395489-19d6a5dc-be6e-4c69-b50a-927e51ba6cec.PNG)

Über dem ersten Eintrag der Challenges erscheint eine Schattierung. Die Anzeige sollte hier homogen sein.

**Comment by Sratschka** [comment]
ist das Verhalten in der aktuellen Version noch vorhanden?
