### ISSUE TITLE
Bestätigung by Friend - Auswahl nicht nachvollziehbar

### ISSUE THREAD

**Issue by winfep** [LosWochos76/StudyBuddy#212]
![InkedBestaetigung_By_Friend_LI](https://user-images.githubusercontent.com/82937602/169159390-84407963-92ba-4c03-a9a3-6c0663ccbb04.jpg)

Wenn eine Challenge durch mit Bestätigung by Friend bestätigt werden soll, dann wird nur ein einziger "Freund" angezeigt. Es ist nicht möglich auszuwählen, welcher Freund angefragt werden soll. Nur, wenn auf "Nein" geklickt wird und erneut auf "Herausforderungen abschließen" wird ein anderer Freund angezeigt. Es ist dann aber auch nicht klar, welcher Freund als nächstes kommt.

Ziel: Auswahl eines Freundes, von dem man die Bestätigung erhalten möchte.

Kurzfristige Lösung: Info im Text, dass mit erneuten Klicken auf "Herausforderung abschließen" ein anderer Freund ausgewählt werden kann, falls man "Nein" anklicken sollte.

**Comment by Smil3MoreGH** [comment]
Sollte mir dem commit Eingefügt sein.
Es wird nur bei Challenges mit dem ChallengeProve "ByFriend" Tag ein Picker angezeigt in dem man einen Freund auswählen kann.
6b1a92e4c4ee16cab4c023081f8d82800aac9e2b

**Comment by Smil3MoreGH** [comment]
Es müsste einmal für Android und vor allem IOS gebaut werden, um es zu testen.
