### ISSUE TITLE
Ändern Bezeichnung Button bei Entfernen von Freunden

### ISSUE THREAD

**Issue by winfep** [LosWochos76/StudyBuddy#213]
![Farbwahl_Freundefinden](https://user-images.githubusercontent.com/82937602/169159529-0d835932-6eb5-4238-89ea-224f074c83b4.png)

Beim Entfernen von Freunden sollte auf dem Button "Entfernen" und nicht "Abbrechen" stehen.

**Comment by Sratschka** [comment]
Den Button mit der Aufschrift "Abbrechen" finde ich bei mir nur auf der Seite zum Senden von Freundschaftsanfragen, der Button dort bricht die gesendete Anfrage ab. Wenn ich mir einen Freund aus der Liste meiner Freunde anschaue ist der Button korrekt beschriftet.
![friendrequests](https://user-images.githubusercontent.com/65534758/169509261-bafea189-02fe-4c54-88e3-4e34ca8a434b.PNG)

**Comment by Sratschka** [comment]
Soll der Button zum Abbrechen der Anfragen anders beschriftet werden?
