### ISSUE TITLE
API stürzt ab

### ISSUE THREAD

**Issue by Sratschka** [LosWochos76/StudyBuddy#232]
Anfragen der App scheinen die API abstürzen zu lassen. Ursache finden und beheben. Hängt möglicherweise mit dem Abrufen nicht vorhandener Daten aus der DB zusammen.

**Comment by Sratschka** [comment]
Wenn man in der App in der statisticsview auf challenges tippt sagt einem die view dass man keine challenges abgeschlossen hat. Wenn man aber auf Abzeichen tippt stürzt die API wegen einer null reference exception in der Formreader Funktion im Gamebadgerepo ab

**Comment by LosWochos76** [comment]
Scheint behoben. Lag wohl eher an den Cron-Mechanismen.
