### ISSUE TITLE
Abzeichen werden nicht richtig angezeigt

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#238]
Der GameBadgeService scheint nicht das richtige Ergebnis zu liefern.

**Comment by LosWochos76** [comment]
In den Zeilen 93-116 des StatisticsPage.xaml wird ein irgendwie fest verdrahtetes Badge angezeigt. Da stimmt etwas nicht. Was soll da angezueigt werden, wenn der Nutzer noch garkein Badge hat? Welches Badge soll da angezeigt werden, wenn der Nutzer bereits eines hat?

**Comment by Smil3MoreGH** [comment]
Die Abzeichen werden nun korrekt angezeit. Es gibt keine Icons für unsere alten Abzeichen, weil niemand diese hinzugefügt hat. Die Abzeichen stammen aus einer Zeit, in der es noch keine Icons gab.

Evtl. mal überlegen, ob wir einmal alle Badges löschen und dann echte Badges für den offiziellen "Start" der App verwenden.

**Comment by Smil3MoreGH** [comment]
siehe commit: ebea3963eb22fac4969c77de0ed93d2dc782c067
