### ISSUE TITLE
App stürzt ab, wenn die API down ist

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#239]
Leider stürzt aktuell die API ja regelmäßig ab.
Dummerweise stürzt dann auch die App ohne Fehlermeldung ab.
Ich hatte gehofft, dass dies nicht passiert, weil das ähnlich ist zu dem Problem, dass kein Internet vorhanden ist.
Das ist aber nicht so.
Die App darf in einem solchen Fall nicht einfach abstürzen!

**Comment by Smil3MoreGH** [comment]
Ich habe eine neue Methode gebaut, die nicht nur prüft, ob das Telefon eine Internetverbindung hat, sondern auch die Erreichbarkeit unserer API-URL überprüft.

Siehe commit: 09bc325ebc415fa314ab7103e91c29858078b33d
