### ISSUE TITLE
Button „Herausforderung abschließen“ nicht lesbar

### ISSUE THREAD

**Issue by winfep** [LosWochos76/StudyBuddy#244]
![3EECCFC2-ECE6-4419-9BC5-EA2AEF69365A](https://user-images.githubusercontent.com/82937602/178542019-bcc50233-e3ab-4c32-bfc2-d2d513e415f5.png)

Der Button „Herausforderung abschließen“ ist in der App kaum lesbar. Sinnvolle Beschriftung wählen, die man auch lesen kann.

**Comment by Sratschka** [comment]
Button wechselt jetzt wie geplant die Hintergrundfarbe bei Themewechsel.
