### ISSUE TITLE
Profil bearbeiten nicht abschließbar bei Klick in Passwort

### ISSUE THREAD

**Issue by winfep** [LosWochos76/StudyBuddy#248]
![3496A356-5978-43B6-B1A8-0E8161A0EF54](https://user-images.githubusercontent.com/82937602/178545203-403a14ec-37b2-47fd-bce6-1eea0044d950.png)

Wenn man das Profil bearbeitet und aus Versehen in Passwort klickt, dann muss man ein neues Passwort setzen. Man kann die Seite nicht mehr verlassen ohne eine Änderung.

**Comment by Sratschka** [comment]
Über den Pfeil oben links sollte man zurück kommen, es gibt jetzt auch einen Abbrechen Button
