### ISSUE TITLE
Verifikationsbutton einfügen bei Bearbeitung von Nutzern im Backend durch Administratoren

### ISSUE THREAD

**Issue by winfep** [LosWochos76/StudyBuddy#257]
Wenn ein Benutzer nicht verifiziert ist, sollten Administratoren im Backend die Möglichkeit besitzen, bei der Bearbeitung des Benutzers den Status auf verifiziert zu setzen. Hierzu soll im Backend bei der Bearbeitung von Nutzern ein entsprechender Button hinzugefügt werden.

**Comment by LosWochos76** [comment]
Admins sollte generell den Status "verifiziert" und "aktiv" setzen können.

**Comment by LosWochos76** [comment]
Done.
