### ISSUE TITLE
Im Backend können Benachrichtigungen nicht verwaltet werden

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#259]
Im Backend gibt es für Admins keine Möglichkeit, auf Benachrichtigungen zuzugreifen.
Im Backend sollten aber ALLE Daten des Systems verwaltet werden können.

**Comment by LosWochos76** [comment]
Benachrichtigungen können jetzt angezeigt und gelöscht werden.
Es fehlt aber noch der Zugang zu den verlinkten MetaDaten und den Kommentaren.

**Comment by AndreasCaldewei** [comment]
Metadaten sind jetzt da und können gelöscht werden
