### ISSUE TITLE
Feststecken bei Infotext

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#45]
Wenn man einmal auf Infos gekommen ist, gibt es keine Möglichkeit über einen Button zurück auf Herausforderung und Co zukommen

Dato geht das nur durch zurückgehen auf die vorherige Seite

**Comment by LosWochos76** [comment]
War tatsächlich ein Bug. In den Hyperlinks zum Impressum usw. wurde ein regulärer Hyperlink genutzt, so dass die Angular App neu geladen wurde. Entsprechend war dann aber auch der Login-State gelöscht, was auch das Menü am oberen Rand entfernt hat. Habe das auf die routerLinks umgestellt. Nun geht es.
