### ISSUE TITLE
Überlappung Informationsleiste mit Buttons bei „Herausforderung“ 

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#48]
Beim Anlegen und der Bearbeitung von Herausforderungen überlappt die untere Informationsleiste die Buttons „Abbrechen“ und „Ok“

![Bild2](https://user-images.githubusercontent.com/85349413/131860103-a2e0c9e6-97c1-4eaa-bdc7-bec030054177.png)

**Comment by LosWochos76** [comment]
Ist in 0.0.8 behoben.
