### ISSUE TITLE
Fehlermeldung spezifizieren, wenn beim Anlegen einer Herausforderung das Ende der Gültigkeit hinter dem Datum des Anfangs liegt

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#53]
Bis jetzt Fehlermeldung: "Der Zeitraum ist nicht gültig!"

Klarere Fehlermeldung: „Das Ende der Herausforderung muss mindestes einen Tag nach dem Anfang liegen!“

**Comment by Smil3MoreGH** [comment]
Fehlermeldung wurde spezifiziert in e2c622e.
Aktuell wird nur geschaut ob das Ende mindestens der gleiche Tag wie der Start ist.
Eventuell weitere Überprüfungen einfügen? (min. Laufzeit, maximal ... Tage in der Zukunft usw...)
