### ISSUE TITLE
Um ein Team anzulegen, sollten mindestens zwei Mitglieder hinzugefügt werden

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#64]
Dato auch Team mit nur einem Mitglied anlegbar

**Comment by LosWochos76** [comment]
Sehe ich etwas anders. Evtl. legt man in Zukunft erstmal ein Team an und lädt dann später Personen dazu ein. Die eigentliche Musik dazu wird sich sowieso in der App abspielen und nicht im Backend.
