### ISSUE TITLE
Beweiserbringung Herausforderung "Bestätigung eines Teammitglieds" durch "Bestätigung eines Dritten" ersetzen

### ISSUE THREAD

**Issue by CharlotteLueb** [LosWochos76/StudyBuddy#73]

**Comment by LosWochos76** [comment]
Ich empfinde "Bestätigung eines Dritten" als weniger präzise, als "Bestätigung eines Teammitglieds". Wer ist ein "Dritter"?

**Comment by CharlotteLueb** [comment]
Ich dachte hier zum Beispiel an die Bestätigung durch einen Studienberater nach einem Beratungsgespräch. Aber das würde natürlich auch mithilfe eines QR Codes gehen. 
Wenn es sich nur um die Beweiserbringungen bei Teams handeln wird, ist "Bestätigung eines Teammitglieds" in der Tat passender.

**Comment by LosWochos76** [comment]
Das ganze Konzept von Teams wurde mittlerweile durch "Freunde" ersetzt. Der Text sollte daher in "Bestätigung eines Freundes" umbenannt werden.
