### ISSUE TITLE
Punktestatistik

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#77]
Ein Nutzer hat die Möglichkeit, seine eigene Punktestatistik zu sehen.
Es werden die Gesamtpunkte in den drei Kategorien "Lernen", "Organisieren" und "Netzwerken" unterschieden.
Für die Teams, in denen man Mitglied ist, werden Rankings angezeigt.

**Comment by LosWochos76** [comment]
Zudem werden auch die Abzeichen angezeigt, die man bereits besitzt.

Optional können Abzeichen angezeigt werden, die man bald erhält, wenn man bestimmte Dinge macht.

**Comment by CharlotteLueb** [comment]
- [ ] #144 
- [ ] #145
- [ ] #152
