### ISSUE TITLE
Ereignislogging

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#78]
Wichtige Ereignisse in der App werden per Loggig-Service aufgezeichnet.

Dazu zählt:
- Aktivieren der App, Einloggen, ansehen von neuen Herausforderungen, Akzeptieren einer Herausforderung, ansehen der Statistik, ...

Der Logging-Service soll die Art des Ereignisses, den Nutzer, die Geo-Daten und die Uhrzeit aufzeichnen.

**Comment by LosWochos76** [comment]
Im Backend ist nun im Menü "Stammdaten" (sollte evtl. in Administration umbenannt werden) ein Punkt "Logging". Dort kann man sich die Meldungen in der DB ansehen und löschen.

**Comment by CharlotteLueb** [comment]
allles was #130 hier hinterlegt ist, sollte getrackt werden
