### ISSUE TITLE
Neuigkeiten

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#79]
Der Nutzer wird nach dem Einloggen als erstes auf eine Kachel "Neuigkeiten" geführt.

Hier sieht er, wenn neue Herausforderungen bzw. Abzeichen für Ihn aktiviert wurden.
Auch sieht er hier, wenn Teammitglieder Herausforderungen angenommen, oder Abzeichen erhalten haben.

Optional:
- Wenn man auf eine solche Neuigkeit klickt, erscheinen zusätzliche Möglichkeiten, z.B. die Herausforderung direkt annehmen, bzw. was man machen muss, um das Abzeichen zu erhalten.
- Wenn ein anderer Nutzer aus einem Team eine Herausforderung oder ein Abzeichen erhalten hat, kann man das hier "liken".

Es muss dazu eine eigene Modellklasse erstellt werden, dessen Objekte durch einen neuen RESTFul Service geliefert werden.
Zunächst ist ein Stub dazu in der App zu entwickeln.

**Comment by CharlotteLueb** [comment]
Dato fehlt nur noch die Möglichkeit Neuigkeiten die man erhält, zu liken. Wie dies aussehen soll und umgesetzt werden kann muss noch diskutiert werden.
