### ISSUE TITLE
Passwort zurücksetzen

### ISSUE THREAD

**Issue by LosWochos76** [LosWochos76/StudyBuddy#82]
Über die Api soll es möglich sein, eine E-Mail zum zurücksetzen der eigenen E-Mail-Adresse zu versenden.
Die E-Mail soll einen Link beinhalten, über den man auf das Backend weitergeleitet wird.
Dort kann man in einem Formular ein neues Passwort eingeben.
Der generierte Link darf nicht zu erraten sein.

**Comment by CharlotteLueb** [comment]
siehe #195

**Comment by LosWochos76** [comment]
Wie ist da der Stand?

**Comment by Sratschka** [comment]
Der Prozess sollte so weit funktionieren, sobald die email verification implementiert ist und alles ausführlich getestet wurde können die issues geschlossen werden

**Comment by Sratschka** [comment]
Funktioniert sowohl in der App als auch im Backend
